#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\userController::isLogged

salvaEvento:
  path: /salvaEvento
  controller: App\Controller\eventController::salvaEvento

calendarioUtente:
  path: /calendar/{username}
  controller: App\Controller\mainController::generaPaginaUtente

listaEventiUtente:
  path: /eventList/{username}
  controller: App\Controller\mainController::generaListaEventi


